# Generated by Django 2.2.4 on 2019-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('author', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=60, null=True)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('push_message_all', models.IntegerField()),
                ('push_message_good', models.IntegerField()),
                ('push_message_bad', models.IntegerField()),
                ('push_message_neutral', models.IntegerField()),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Analysis',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('article', models.IntegerField()),
                ('discussion', models.IntegerField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('score', models.FloatField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Yahoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
