# Generated by Django 2.2.4 on 2019-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICLE',
            fields=[
                ('author', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('push_message_all', models.IntegerField()),
                ('push_message_good', models.IntegerField()),
                ('push_message_bad', models.IntegerField()),
                ('push_message_neutral', models.IntegerField()),
            ],
        ),
    ]
