# Generated by Django 2.2.4 on 2019-09-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword_Analysis',
        ),
    ]
