# Generated by Django 2.2.4 on 2019-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Yahoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='ip',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
