# Generated by Django 2.2.4 on 2019-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0002_auto_20190827_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_yahoo',
            name='keyword',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
