# Generated by Django 2.2.4 on 2019-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0003_auto_20190827_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('keyword', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
