# Generated by Django 2.2.4 on 2019-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0003_keyword_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='not_keyword',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
