# Generated by Django 2.2.4 on 2019-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0004_keyword_not_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Analysis_Month',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('article', models.IntegerField()),
                ('discussion', models.IntegerField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('score', models.FloatField()),
                ('comment', models.CharField(max_length=10)),
            ],
        ),
    ]
