# Generated by Django 2.2.4 on 2019-10-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_movie', '0005_keyword_analysis_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword_Analysis_Month',
        ),
    ]
